import type { Emotion, SpecificEmotion } from '@/types/shared/emotions';

export const emotions: { [key: string]: Emotion } = {
  anxiety: {
    name: 'anxiety',
    displayName: 'Anxiety',
    description: 'Feelings of worry, nervousness, or unease about something.',
    color: '#FFD700', // Gold/yellow - represents alertness and tension
  },
  sadness: {
    name: 'sadness',
    displayName: 'Sadness',
    description: 'Feelings of sorrow, unhappiness, or emotional pain.',
    color: '#4682B4', // Steel blue - represents melancholy and depth
  },
  anger: {
    name: 'anger',
    displayName: 'Anger',
    description: 'Feelings of strong displeasure, hostility, or antagonism.',
    color: '#DC143C', // Crimson - represents intensity and heat
  },
  shame: {
    name: 'shame',
    displayName: 'Shame',
    description: 'Feelings of humiliation, guilt, or self-consciousness.',
    color: '#800080', // Purple - represents heaviness and introspection
  },
  fear: {
    name: 'fear',
    displayName: 'Fear',
    description: 'Feelings of being afraid, scared, or threatened.',
    color: '#2F4F4F', // Dark slate gray - represents uncertainty and darkness
  },
  disgust: {
    name: 'disgust',
    displayName: 'Disgust',
    description: 'Feelings of revulsion, aversion, or strong disapproval.',
    color: '#556B2F', // Dark olive green - represents nausea and distaste
  },
  positive: {
    name: 'positive',
    displayName: 'Positive',
    description: 'Feelings of happiness, contentment, or optimism.',
    color: '#32CD32', // Lime green - represents growth and vitality
  },
};

export const specificEmotions: SpecificEmotion[] = [
  {
    name: 'anxious',
    displayName: 'Anxious',
    description: 'A general sense of unease or nervous anticipation.',
    category: emotions.anxiety,
    isNegative: true,
  },
  {
    name: 'nervous',
    displayName: 'Nervous',
    description: 'Feeling jittery or unsettled, often before an event.',
    category: emotions.anxiety,
    isNegative: true,
  },
  {
    name: 'worried',
    displayName: 'Worried',
    description: 'Concerned about possible negative outcomes.',
    category: emotions.anxiety,
    isNegative: true,
  },
  {
    name: 'apprehensive',
    displayName: 'Apprehensive',
    description: 'Uneasy about something that might happen.',
    category: emotions.anxiety,
    isNegative: true,
  },
  {
    name: 'panicked',
    displayName: 'Panicked',
    description: 'Overcome with sudden fear or anxiety.',
    category: emotions.anxiety,
    isNegative: true,
  },
  {
    name: 'overwhelmed',
    displayName: 'Overwhelmed',
    description: 'Feeling mentally or emotionally overloaded.',
    category: emotions.anxiety,
    isNegative: true,
  },
  {
    name: 'sad',
    displayName: 'Sad',
    description: 'A feeling of unhappiness or sorrow.',
    category: emotions.sadness,
    isNegative: true,
  },
  {
    name: 'down',
    displayName: 'Down',
    description: 'Low in mood but not necessarily crying or despondent.',
    category: emotions.sadness,
    isNegative: true,
  },
  {
    name: 'hopeless',
    displayName: 'Hopeless',
    description: 'Feeling that things will never improve.',
    category: emotions.sadness,
    isNegative: true,
  },
  {
    name: 'discouraged',
    displayName: 'Discouraged',
    description: 'Lacking motivation due to setbacks or failures.',
    category: emotions.sadness,
    isNegative: true,
  },
  {
    name: 'lonely',
    displayName: 'Lonely',
    description: 'Feeling socially isolated or emotionally disconnected.',
    category: emotions.sadness,
    isNegative: true,
  },
  {
    name: 'hurt',
    displayName: 'Hurt',
    description: 'Emotionally pained due to words or actions.',
    category: emotions.sadness,
    isNegative: true,
  },
  {
    name: 'angry',
    displayName: 'Angry',
    description: 'A strong feeling of displeasure or hostility.',
    category: emotions.anger,
    isNegative: true,
  },
  {
    name: 'frustrated',
    displayName: 'Frustrated',
    description: 'Blocked from achieving something; annoyed.',
    category: emotions.anger,
    isNegative: true,
  },
  {
    name: 'irritated',
    displayName: 'Irritated',
    description: 'Mild anger or annoyance.',
    category: emotions.anger,
    isNegative: true,
  },
  {
    name: 'resentful',
    displayName: 'Resentful',
    description: 'Holding bitterness from perceived unfairness.',
    category: emotions.anger,
    isNegative: true,
  },
  {
    name: 'enraged',
    displayName: 'Enraged',
    description: 'Intensely furious or incensed.',
    category: emotions.anger,
    isNegative: true,
  },
  {
    name: 'betrayed',
    displayName: 'Betrayed',
    description: 'Feeling deeply hurt by broken trust.',
    category: emotions.anger,
    isNegative: true,
  },
  {
    name: 'embarrassed',
    displayName: 'Embarrassed',
    description: 'Self-conscious due to a perceived mistake or exposure.',
    category: emotions.shame,
    isNegative: true,
  },
  {
    name: 'ashamed',
    displayName: 'Ashamed',
    description: 'Feeling bad about oneself for something done.',
    category: emotions.shame,
    isNegative: true,
  },
  {
    name: 'guilty',
    displayName: 'Guilty',
    description: 'Feeling responsible for a wrongdoing.',
    category: emotions.shame,
    isNegative: true,
  },
  {
    name: 'inadequate',
    displayName: 'Inadequate',
    description: 'Feeling not good enough or lacking ability.',
    category: emotions.shame,
    isNegative: true,
  },
  {
    name: 'worthless',
    displayName: 'Worthless',
    description: 'Feeling of no value or significance.',
    category: emotions.shame,
    isNegative: true,
  },
  {
    name: 'afraid',
    displayName: 'Afraid',
    description: 'Fearful of a threat or danger.',
    category: emotions.fear,
    isNegative: true,
  },
  {
    name: 'scared',
    displayName: 'Scared',
    description: 'Frightened or panicked by perceived danger.',
    category: emotions.fear,
    isNegative: true,
  },
  {
    name: 'terrified',
    displayName: 'Terrified',
    description: 'Intense fear and alarm.',
    category: emotions.fear,
    isNegative: true,
  },
  {
    name: 'insecure',
    displayName: 'Insecure',
    description: 'Lacking confidence or feeling unsafe.',
    category: emotions.fear,
    isNegative: true,
  },
  {
    name: 'helpless',
    displayName: 'Helpless',
    description: 'Unable to take control or influence events.',
    category: emotions.fear,
    isNegative: true,
  },
  {
    name: 'disgusted',
    displayName: 'Disgusted',
    description: 'Strong aversion or revulsion.',
    category: emotions.disgust,
    isNegative: true,
  },
  {
    name: 'contemptuous',
    displayName: 'Contemptuous',
    description: 'Feeling superior and dismissive toward others.',
    category: emotions.disgust,
    isNegative: true,
  },
  {
    name: 'repulsed',
    displayName: 'Repulsed',
    description: 'Driven away by something offensive or sickening.',
    category: emotions.disgust,
    isNegative: true,
  },
  {
    name: 'relieved',
    displayName: 'Relieved',
    description: 'Feeling better after worry or stress subsides.',
    category: emotions.positive,
    isNegative: false,
  },
  {
    name: 'hopeful',
    displayName: 'Hopeful',
    description: 'Expecting a positive outcome.',
    category: emotions.positive,
    isNegative: false,
  },
  {
    name: 'content',
    displayName: 'Content',
    description: 'Peaceful satisfaction with the present.',
    category: emotions.positive,
    isNegative: false,
  },
  {
    name: 'proud',
    displayName: 'Proud',
    description: 'Satisfied and dignified about accomplishments.',
    category: emotions.positive,
    isNegative: false,
  },
  {
    name: 'confident',
    displayName: 'Confident',
    description: 'Feeling capable and self-assured.',
    category: emotions.positive,
    isNegative: false,
  },
];
